name: test publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-preview[0-9]+"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v./}" >> $GITHUB_ENV

    - name: dotnet publish
      run: dotnet publish --configuration=Release -r linux-musl-x64 --self-contained -o ./publish/

    - name: log into scw container registry
      uses: docker/login-action@v2
      with:
        registry: rg.fr-par.scw.cloud/onx-private
        username: nologin
        password: ${{ secrets.SCW_SECRET }}

    - name: Build and push docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: "rg.fr-par.scw.cloud/onx-private/proj1:${VERSION}"
